import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import AuthSync from "@/components/auth/AuthSync";
import { Suspense } from "react";



const beVietnam = Be_Vietnam_Pro({
  subsets: ["vietnamese"],
  weight: ["400","500","600","700"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body>
        <Suspense fallback={null}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}

